NORTH = 0
EAST = 1
SOUTH = 2
WEST = 3




#object tile indices
OBJECT_TABLE=20
OBJECT_MEDTABLE=21
OBJECT_BLOODSMALL=22
OBJECT_BLOODLARGE=23
OBJECT_CRATE=24

#decal tile indices
DECAL_DOOR=80
DECAL_DCODE_G=82
DECAL_DCODE_R=83
DECAL_DKEY_G=84
DECAL_DKEY_R=85
DECAL_BLOOD_SM=86
DECAL_BLOOD_BIG=87
DECAL_SWITCH1=88
DECAL_SWITCH2=89